### ISSUE TITLE
error

### ISSUE THREAD

**Issue by fsteamID** [New-dev0/TgTwitterStreamer#4]
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/firdaus/Documents/Telegram/telebot/TgTwitterStreamer/TgTwitterStreamer/__init__.py", line 23, in <module>
    auth = OAuthHandler(Var.CONSUMER_KEY, Var.CONSUMER_SECRET)
  File "/home/firdaus/.local/lib/python3.9/site-packages/tweepy/auth.py", line 36, in __init__
    raise TypeError("Consumer key must be string or bytes, not "
TypeError: Consumer key must be string or bytes, not NoneType

**Comment by New-dev0** [comment]
Make sure that, you have filled all Mandatory environment variables.
